-- MySQL Script generated by MySQL Workbench
-- Mon Feb  9 13:15:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reservation_salles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservation_salles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS reservation_salles DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE reservation_salles ;

-- -----------------------------------------------------
-- Table reservation_salles.users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS reservation_salles.users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table reservation_salles.reservations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS reservation_salles.reservations (
  id INT NOT NULL AUTO_INCREMENT,
  titre VARCHAR(255) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  debut DATETIME NOT NULL,
  fin DATETIME NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  users_id INT NOT NULL,
  PRIMARY KEY (id, users_id),
  INDEX fk_reservations_users_idx (users_id ASC) VISIBLE,
  CONSTRAINT fk_reservations_users
    FOREIGN KEY (users_id)
    REFERENCES reservation_salles.users (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-----------------------------------------------------
-- jeu de données
-- -----------------------------------------------------

INSERT INTO `reservation_salles`.`users` (`id`, `email`, `password`, `created_at`) VALUES (1, 'admin@reservation-salle.fr', 'admin', '2026-02-09 13:15:26');
INSERT INTO `reservation_salles`.`users` (`id`, `email`, `password`, `created_at`) VALUES (2, 'user@reservation-salle.fr', 'user', '2026-02-09 13:15:26');
INSERT INTO `reservation_salles`.`reservations` (`id`, `titre`, `description`, `debut`, `fin`, `created_at`, `users_id`) VALUES (1, 'Réunion de projet', 'Discussion sur les étapes du projet', '2026-02-10 10:00:00', '2026-02-10 11:00:00', '2026-02-09 13:15:26', 1);
INSERT INTO `reservation_salles`.`reservations` (`id`, `titre`, `description`, `debut`, `fin`, `created_at`, `users_id`) VALUES (2, 'Formation', 'Session de formation pour les nouveaux employés', '2026-02-11 14:00:00', '2026-02-11 16:00:00', '2026-02-09 13:15:26', 2);